### ISSUE TITLE
building on coq master

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [sifive/RiscvSpecFormal#14]
I am trying to get RiscvSpecFormal to build on coq master. Here is the progress so far:

- an earlier ProcKami failed at parsing `Local Record`
- latest ProcKami seems to [fail](https://builds.sr.ht/~andres_tries_srht_github/job/82966) as follows:

```coq
File "./ProcKami/RiscvIsaSpec/Csr/CsrFuncs.v", line 26, characters 2-79:
Warning: Declaring a scope implicitly is deprecated; use in advance an
explicit "Declare Scope local_scope.". [undeclared-scope,deprecated]
File "./ProcKami/RiscvIsaSpec/Csr/CsrFuncs.v", line 180, characters 37-47:
Error:
In environment
name : string
Xlen_over_8, Rlen_over_8 : nat
supported_exts : list (string * bool)
ty : Kind -> Type
view : CsrView
upd_pkt : Expr ty (SyntaxKind CsrFieldUpdGuard)
req : Expr ty (SyntaxKind (LocationReadWriteInputT VAddr))
csr_value : ty (csrKind (csrViewFields view))
input_value : fullType ty (SyntaxKind (csrKind (csrViewFields view)))
field : CsrField
acc : ActionT ty Void
interface : CsrFieldRegister (csrFieldKind field)
The term "Var ty (SyntaxKind (csrKind (csrViewFields view))) csr_value"
has type "Expr ty (SyntaxKind (csrKind (csrViewFields view)))"
while it is expected to have type
 "Expr ty (SyntaxKind (Struct ?get_value ?get_name))".
```

- now building with all submodules bumped https://builds.sr.ht/~andres_tries_srht_github/job/82966
- I think we are close to the RAM limit
- on the positive side, all Haskell dependencies seem to be available pre-built in nixpkgs ([manifest](https://builds.sr.ht/api/jobs/82966/manifest)).

**Comment by andres-erbsen-sifive** [comment]
OOM indeed https://builds.sr.ht/~andres_tries_srht_github/job/83001

**Comment by andres-erbsen-sifive** [comment]
blocked on https://github.com/coq/coq/issues/10684 , after that we can hopefully just use the manifest I posted above

**Comment by andres-erbsen-sifive** [comment]
It looks like the change that caused the memory usage increase is going to stay, so we will need to find another way.

**Comment by tjmach** [comment]
COQC Kami/CVProperties.v
File "./Kami/CVProperties.v", line 593, characters 33-35:
Error:
In environment
l, l' : list DefMethT
HNeverCall : forall (meth : DefMethT) (ty : Kind -> Type),
             In meth l' ->
             forall arg : ty (fst (projT1 (snd meth))),
             NeverCallActionT (projT2 (snd meth) ty arg)
P0 : Datatypes.length l <= Datatypes.length l + Datatypes.length l'
The term "P0" has type
 "Datatypes.length l <= Datatypes.length l + Datatypes.length l'"
while it is expected to have type "nat".

They seem to have done something to change the number of parameters accepted by `seq_app` on line  593.  Seems like it would break more than just Kami, was that deliberate on their part?

**Comment by whonore** [comment]
What version is that? Seems to work with 8.10+alpha.

**Comment by whonore** [comment]
They did make some changes to how implicit arguments are calculated (https://coq.github.io/doc/v8.10/refman/changes.html#other-changes-in-8-10-beta1) so it's possible something there broke it.

**Comment by vmurali** [comment]
This is some unintentional name capture. He had named a similar function seq_app and suddenly they added it into standard lib.

**Comment by tjmach** [comment]
Alright, we're past CompileVerifiable and CVProperties.  I don't know about the rest yet, but that seems like a good sign.

**Comment by tjmach** [comment]
Oh, well that was short, now kami_hs is failing.

https://builds.sr.ht/~amach/job/83331

**Comment by vmurali** [comment]
I modified the script considerably. Did you not pull?

**Comment by tjmach** [comment]
There's a version of the script which doesn't have the /bin/bash shebang?  I pulled before pushing the CV breakup and didn't see it, maybe I screwed something up?
